services:
  postgres:
    container_name: postgres-sql-cpn
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PG-DATA: /var/lib/postgresql/data
      POSTGRES_DB: car_passion_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres:
    driver: local
